# debian:8.6 - linux; amd64
# https://github.com/docker-library/repo-info/blob/master/repos/debian/tag-details.md
FROM debian@sha256:c1af755d300d0c65bb1194d24bce561d70c98a54fb5ce5b1693beb4f7988272f

MAINTAINER Vishnu Mohan <vishnu@mesosphere.com>

ENV CONDA_INSTALLER=Miniconda3-4.2.12-Linux-x86_64.sh \
    CONDA_MD5=874dbb0d3c7ec665adf7231bbb575ab2 \
    CONDA_UID=1000 \
    CONDA_URL=https://repo.continuum.io/miniconda \
    CONDA_USER=conda \
    CONDA_USER_HOME=/home/conda \
    DEBIAN_FRONTEND=noninteractive \
    GPG_KEYSERVER=ha.pool.sks-keyservers.net \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    REPO=http://cdn-fastly.deb.debian.org \
    SHELL=/bin/bash \
    TINI_GPG_KEY=6380DC428747F6C393FEACA59A84159D7001A4E5 \
    TINI_URL=https://github.com/krallin/tini/releases/download \
    TINI_VERSION=v0.10.0

RUN echo "deb $REPO/debian jessie main\ndeb $REPO/debian-security jessie/updates main" \
    > /etc/apt/sources.list \
    && apt-get update -yq --fix-missing && apt-get -yq dist-upgrade \
    && apt-get install -yq --no-install-recommends locales \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen \
    && apt-get install -yq --no-install-recommends \
       bash-completion \
       bzip2 \
       ca-certificates \
       curl \
       git \
       jq \
       libglib2.0-0 \
       libsm6 \
       libxext6 \
       libxrender1 \
       openssh-client \
       sudo \
       unzip \
       vim \
       wget \
    && apt-key adv --keyserver "$GPG_KEYSERVER" --recv-keys "$TINI_GPG_KEY" \
    && apt-get clean \
    && rm -rf /var/apt/lists/*

RUN cd /tmp \
    && curl -fsSL "$TINI_URL/$TINI_VERSION/tini" -o /usr/local/bin/tini \
    && curl -fsSL -O "$TINI_URL/$TINI_VERSION/tini.asc" \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --keyserver "$GPG_KEYSERVER" --recv-keys "$TINI_GPG_KEY" \
    && gpg --batch --verify tini.asc /usr/local/bin/tini \
    && rm -rf "$GNUPGHOME" tini.asc \
    && chmod +x /usr/local/bin/tini \
    && rm -rf /tmp/* \
    && useradd -m -s /bin/bash -g users -N -u "$CONDA_UID" "$CONDA_USER"

USER conda
RUN cd "$CONDA_USER_HOME" \
    && curl -fsSL -O "$CONDA_URL/$CONDA_INSTALLER" \
    && echo "$CONDA_MD5  $CONDA_INSTALLER" | md5sum -c - \
    && bash "./$CONDA_INSTALLER" -b -p "$CONDA_USER_HOME/conda" \
    && rm -f "$CONDA_INSTALLER" \
    && $CONDA_USER_HOME/conda/bin/conda config --system --add channels conda-forge \
    && $CONDA_USER_HOME/conda/bin/conda clean --yes --tarballs --packages \
    && mkdir -p "$CONDA_USER_HOME/work" \
    && mkdir -p "$CONDA_USER_HOME/.jupyter"

WORKDIR "$CONDA_USER_HOME/work"
ENTRYPOINT ["tini", "--"]
CMD ["conda.sh"]

# Add local files as late as possible to stay cache friendly
COPY profile "$CONDA_USER_HOME/.profile"
COPY bash_profile "$CONDA_USER_HOME/.bash_profile"
COPY bashrc "$CONDA_USER_HOME/.bashrc"
COPY dircolors "$CONDA_USER_HOME/.dircolors"
COPY conda-home.sh /usr/local/bin/conda.sh
